### ISSUE TITLE
Precompile - Segmentation Fault 2.3.0

### ISSUE THREAD

**Issue by Mafaka8** [fireice-uk/xmr-stak#1225]
Is there some way to disable the precompile? 

Every time I try to create two thread configurations for one GPU I end up with a segmentation fault.

**Comment by Mafaka8** [comment]
Its kinda strange. On one rig with Ubuntu I have three of the same GPU and there is no problem everything works properly. The other rig is CentOS, I have 5 GPUs the minute that I try to use two configs for any of the 5 I get the segmentation fault when xmr-stak tries to load the precompiled binary that it just created.

**Comment by Mafaka8** [comment]
[2018-03-27 00:29:38] : MEMORY ALLOC FAILED: mmap failed
[2018-03-27 00:29:38] : MEMORY ALLOC FAILED: mmap failed
[2018-03-27 00:29:38] : MEMORY ALLOC FAILED: mmap failed
[2018-03-27 00:29:38] : MEMORY ALLOC FAILED: mmap failed
[2018-03-27 00:29:38] : MEMORY ALLOC FAILED: mmap failed
-------------------------------------------------------------------
xmr-stak 2.3.0 a036cd8

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-03-27 00:29:38] : Mining coin: monero7
[2018-03-27 00:29:38] : Compiling code and initializing GPUs. This will take a while...
[2018-03-27 00:29:38] : Device 0 work size 8 / 32.
[2018-03-27 00:29:38] : OpenCL device 0 - Precompiled code /root/.openclcache/ee747415d84cbcaedc2b4507d66775ebb2848c1778d536a7d0dce041771d9b23.openclbin not found. Compiling ...
/root/.openclcache/ee747415d84cbcaedc2b4507d66775ebb2848c1778d536a7d0dce041771d9b23.openclbin
[2018-03-27 00:29:49] : OpenCL device 0 - Precompiled code stored in file /root/.openclcache/ee747415d84cbcaedc2b4507d66775ebb2848c1778d536a7d0dce041771d9b23.openclbin
[2018-03-27 00:29:49] : Device 0 work size 8 / 32.
[2018-03-27 00:29:49] : OpenCL device 0 - Load precompiled cod from file /root/.openclcache/ee747415d84cbcaedc2b4507d66775ebb2848c1778d536a7d0dce041771d9b23.openclbin
./1-start: line 8:  6288 Segmentation fault      (core dumped) ./xmr-stak --amd amd.txt

**Comment by Mafaka8** [comment]
"gpu_threads_conf" : [
  // gpu: Fiji memory:3049
  // compute units: 64
  { "index" : 0, "intensity" : 960, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2, "comp_mode" : true },
  { "index" : 0, "intensity" : 960, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2, "comp_mode" : true },

  // gpu: Hawaii memory:3049
  // compute units: 40
  { "index" : 1, "intensity" : 960, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2, "comp_mode" : true },
  { "index" : 1, "intensity" : 960, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2, "comp_mode" : true },

  // gpu: Ellesmere memory:3920
  // compute units: 36
  { "index" : 2, "intensity" : 1152, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2, "comp_mode" : true },
  { "index" : 2, "intensity" : 1152, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2, "comp_mode" : true },

  // gpu: Ellesmere 1 memory:3920
  // compute units: 36
  { "index" : 3, "intensity" : 1024, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2, "comp_mode" : false },
  { "index" : 3, "intensity" : 1024, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2, "comp_mode" : false },

  // gpu: Tonga memory:3050
  // compute units: 28
  { "index" : 4, "intensity" : 640, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2, "comp_mode" : true },
  { "index" : 4, "intensity" : 640, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2, "comp_mode" : true },

],

**Comment by psychocrypt** [comment]
Could it by that you are using two prosesses per gpu (start the miner two
times) instead of using one miner and add two lines per gpu to the config?

**Comment by psychocrypt** [comment]
sry don:t saw that you really configured two threads. could you please cal
`rm /root/.openclcache` to remove all old cache files. Than start the miner
and post the output of both starts please.

**Comment by Mafaka8** [comment]
I have done that lol i actually added a line in my start script to delete the .openclcache folder before running xmr-stak so that it will start fresh every time.

**Comment by Mafaka8** [comment]
its like the miner has problems loading the precompiled code for the second thread.

**Comment by Mafaka8** [comment]
I just tried a new install from scratch. cloned with git. Look at this - two of my GPUs are identified as Elsemere. one is an RX 580 the other an RX 480. There appears to be a problem with the fact that they are both identified the same way

**Comment by Mafaka8** [comment]
Pool configuration stored in file 'pools.txt'
[2018-03-27 00:46:04] : MEMORY ALLOC FAILED: mmap failed
[2018-03-27 00:46:04] : MEMORY ALLOC FAILED: mmap failed
[2018-03-27 00:46:04] : MEMORY ALLOC FAILED: mmap failed
[2018-03-27 00:46:04] : MEMORY ALLOC FAILED: mmap failed
[2018-03-27 00:46:04] : MEMORY ALLOC FAILED: mmap failed
-------------------------------------------------------------------
xmr-stak 2.3.0 a036cd8

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-03-27 00:46:04] : Mining coin: monero7
[2018-03-27 00:46:05] : Found AMD platform index id = 0, name = Advanced Micro Devices, Inc.
[2018-03-27 00:46:05] : Found OpenCL GPU Fiji.
[2018-03-27 00:46:05] : Found OpenCL GPU Hawaii.
[2018-03-27 00:46:05] : Found OpenCL GPU Ellesmere.
[2018-03-27 00:46:05] : Found OpenCL GPU Ellesmere.
[2018-03-27 00:46:05] : Found OpenCL GPU Tonga.
[2018-03-27 00:46:05] : AMD: GPU configuration stored in file 'amd.txt'
[2018-03-27 00:46:05] : Compiling code and initializing GPUs. This will take a while...
[2018-03-27 00:46:05] : Device 0 work size 8 / 32.
[2018-03-27 00:46:05] : OpenCL device 0 - Precompiled code /root/.openclcache/e84b19025965ac5f4296fc19b6df55de888c903a53a6b001aa046ab6e130b853.openclbin not found. Compiling ...
/root/.openclcache/e84b19025965ac5f4296fc19b6df55de888c903a53a6b001aa046ab6e130b853.openclbin
[2018-03-27 00:46:15] : OpenCL device 0 - Precompiled code stored in file /root/.openclcache/e84b19025965ac5f4296fc19b6df55de888c903a53a6b001aa046ab6e130b853.openclbin
[2018-03-27 00:46:15] : Device 1 work size 8 / 32.
[2018-03-27 00:46:15] : OpenCL device 1 - Precompiled code /root/.openclcache/b206615977bcddb4005265f80aa5595572774bdb2b24a26a052876c6985ba65f.openclbin not found. Compiling ...
/root/.openclcache/b206615977bcddb4005265f80aa5595572774bdb2b24a26a052876c6985ba65f.openclbin
[2018-03-27 00:46:25] : OpenCL device 1 - Precompiled code stored in file /root/.openclcache/b206615977bcddb4005265f80aa5595572774bdb2b24a26a052876c6985ba65f.openclbin
[2018-03-27 00:46:25] : Device 2 work size 8 / 32.
[2018-03-27 00:46:25] : OpenCL device 2 - Precompiled code /root/.openclcache/b310624ad18fba805c6e2ed79fa373313b2625886f8c6979e0e3179752af5bb2.openclbin not found. Compiling ...
/root/.openclcache/b310624ad18fba805c6e2ed79fa373313b2625886f8c6979e0e3179752af5bb2.openclbin
[2018-03-27 00:46:36] : OpenCL device 2 - Precompiled code stored in file /root/.openclcache/b310624ad18fba805c6e2ed79fa373313b2625886f8c6979e0e3179752af5bb2.openclbin
[2018-03-27 00:46:36] : Device 3 work size 8 / 32.
[2018-03-27 00:46:36] : OpenCL device 3 - Load precompiled cod from file /root/.openclcache/b310624ad18fba805c6e2ed79fa373313b2625886f8c6979e0e3179752af5bb2.openclbin
Segmentation fault (core dumped)

**Comment by psychocrypt** [comment]
Please remove this line from your script. Remove the cache by hand and
start the miner two times and post the output. Also ease post the script. I
need both to reproduce the issue.

**Comment by Mafaka8** [comment]
it would appear as though on CentOS the minute the miner runs into a duplicate in the amd.txt file it dies.

**Comment by Mafaka8** [comment]
I have tried deleting .openclcache by hand and also with my script both do not work as the minute it tries to load precompiled binary for the second thread I get the segmentation fault

**Comment by Mafaka8** [comment]
Here is what I use as a start script. 

#!/bin/bash
export GPU_FORCE_64BIT_PTR=1
export GPU_USE_SYNC_OBJECTS=1
export GPU_MAX_ALLOC_PERCENT=100
export GPU_SINGLE_ALLOC_PERCENT=100
export GPU_MAX_HEAP_SIZE=100
rm -rf /root/.openclcache
./xmr-stak --amd amd.txt

**Comment by psychocrypt** [comment]
I know that this not helps I really need the output for debugging. This
will not solve the issue now but I need to understand where the iasue is
coming from.

**Comment by Mafaka8** [comment]
The fresh install that I just posted - I simply ran xmr-stak and configured everything manually. Then I let the miner find the GPUs and setup the amd.txt file. it then proceeded to precompile binaries for each GPU but as you saw the minute it hits the second elsemere GPU it trips up

**Comment by Mafaka8** [comment]
I understand and I want to help as much as I can. I love your miner and I want to be able to use this new version that you have come up with on all of my rigs.

**Comment by Mafaka8** [comment]
you know what I found makes it work ?

If I change comp_mode to false for the second thread, then everything works. the problem is that I have two GPUs being identified as elsemere. I can only use true and false once lol so changing comp_mode to false for the second thread for 4 of my 5 GPUs works. but when I change it on the 5th i end up with a duplicate identical entry in amd.txt and this causes the issue to occur.

**Comment by psychocrypt** [comment]
ifyou change one option to false than a new binarie is created. Are both
gpus equal?

**Comment by Mafaka8** [comment]
Here is a test I just ran. 

I setup amd.txt to only have 1 GPU with 2 thread configurations. 


/*
 * GPU configuration. You should play around with intensity and worksize as the fastest settings will vary.
 * index         - GPU index number usually starts from 0
 * intensity     - Number of parallel GPU threads (nothing to do with CPU threads)
 * worksize      - Number of local GPU threads (nothing to do with CPU threads)
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 * strided_index - switch memory pattern used for the scratch pad memory
 *                 2 = chunked memory, chunk size is controlled by 'mem_chunk'
 *                     required: intensity must be a multiple of worksize
 *                 1 or true  = use 16byte contiguous memory per thread, the next memory block has offset of intensity blocks
 *                 0 or false = use a contiguous block of memory per thread
 * mem_chunk     - range 0 to 18: set the number of elements (16byte) per chunk
 *                 this value is only used if 'strided_index' == 2
 *                 element count is computed with the equation: 2 to the power of 'mem_chunk' e.g. 4 means a chunk of 16 elements(256byte)
 * comp_mode     - Compatibility enable/disable the automatic guard around compute kernel which allows
 *                 to use a intensity which is not the multiple of the worksize.
 *                 If you set false and the intensity is not multiple of the worksize the miner can crash:
 *                 in this case set the intensity to a multiple of the worksize or activate comp_mode.
 * "gpu_threads_conf" :
 * [
 *      { "index" : 0, "intensity" : 1000, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : true, "mem_chunk" : 2, "comp_mode" : true },
 * ],
 * If you do not wish to mine with your AMD GPU(s) then use:
 * "gpu_threads_conf" :
 * null,
 */

"gpu_threads_conf" : [
  // gpu: Fiji memory:3049
  // compute units: 64
  { "index" : 0,
    "intensity" : 512, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: Fiji memory:3049
  // compute units: 64
  { "index" : 0,
    "intensity" : 512, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },

],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 0,

then I rm the .openclcache folder and then run xmr-stak and here is the output. 

[root@postman bin]# vi amd.txt
[root@postman bin]# rm -rf /root/.openclcache/
[root@postman bin]# ./xmr-stak
[2018-03-27 01:00:18] : MEMORY ALLOC FAILED: mmap failed
[2018-03-27 01:00:18] : MEMORY ALLOC FAILED: mmap failed
[2018-03-27 01:00:18] : MEMORY ALLOC FAILED: mmap failed
[2018-03-27 01:00:18] : MEMORY ALLOC FAILED: mmap failed
[2018-03-27 01:00:18] : MEMORY ALLOC FAILED: mmap failed
-------------------------------------------------------------------
xmr-stak 2.3.0 a036cd8

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-03-27 01:00:18] : Mining coin: monero7
[2018-03-27 01:00:18] : Compiling code and initializing GPUs. This will take a while...
[2018-03-27 01:00:18] : Device 0 work size 8 / 32.
[2018-03-27 01:00:18] : OpenCL device 0 - Precompiled code /root/.openclcache/e84b19025965ac5f4296fc19b6df55de888c903a53a6b001aa046ab6e130b853.openclbin not found. Compiling ...
/root/.openclcache/e84b19025965ac5f4296fc19b6df55de888c903a53a6b001aa046ab6e130b853.openclbin
[2018-03-27 01:00:29] : OpenCL device 0 - Precompiled code stored in file /root/.openclcache/e84b19025965ac5f4296fc19b6df55de888c903a53a6b001aa046ab6e130b853.openclbin
[2018-03-27 01:00:29] : Device 0 work size 8 / 32.
[2018-03-27 01:00:29] : OpenCL device 0 - Load precompiled cod from file /root/.openclcache/e84b19025965ac5f4296fc19b6df55de888c903a53a6b001aa046ab6e130b853.openclbin
Segmentation fault (core dumped)

**Comment by Mafaka8** [comment]
to answer your question no the elsemere GPUs are not exactly the same, one is a sapphire RX 480 and the other is an Asus RX 580. the miner thinks they are exactly the same though.

**Comment by Mafaka8** [comment]
I really think this holds the key to the answer of this problem. 

if the entries are 100% identical the miner dies. 

"gpu_threads_conf" : [
// gpu: Fiji memory:3049
// compute units: 64
{ "index" : 0,
"intensity" : 512, "worksize" : 8,
"affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
"comp_mode" : true
},
// gpu: Fiji memory:3049
// compute units: 64
{ "index" : 0,
"intensity" : 512, "worksize" : 8,
"affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
"comp_mode" : true
},

],

the strange thing is this is only on my CentOS rig. on my Ubuntu rig I have three of the same GPU with 2 identical threads for each in the amd.txt making for a total of 6 identical entries and everything works fine.

**Comment by Mafaka8** [comment]
this is what I have in the Ubuntu rig. all works fine lol 

"gpu_threads_conf" : [
  // gpu: Tahiti memory:2165
  // compute units: 16
  { "index" : 0, "intensity" : 720, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2, "comp_mode" : true },
  { "index" : 0, "intensity" : 720, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2, "comp_mode" : true },

  // gpu: Tahiti memory:2165
  // compute units: 16
  { "index" : 1, "intensity" : 720, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2, "comp_mode" : true },
  { "index" : 1, "intensity" : 720, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2, "comp_mode" : true },

  // gpu: Tahiti memory:2165
  // compute units: 16
  { "index" : 2, "intensity" : 720, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2, "comp_mode" : true },
  { "index" : 2, "intensity" : 720, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2, "comp_mode" : true },

],

**Comment by Mafaka8** [comment]
Haha I got it to work. You will laugh. Being as the miner looks for .openclcache in the home directory of the user running the miner. I changed where the precompiled binary is stored to /tmp/.openclcache

**Comment by Mafaka8** [comment]
this forces the miner to create a new binary every time but meh it works for now :)

**Comment by Mafaka8** [comment]
in gpu.cpp

I changed the following: 
    std::string cache_file = get_home() + "/.openclcache/" + hash_hex_str + ".openclbin"; */

to:
    std::string cache_file = "/tmp/.openclcache/" + hash_hex_str + ".openclbin";

**Comment by psychocrypt** [comment]
Never the less it is strange why you cant't write to /root. Please check if
your root filesystem is full `df -h`

**Comment by Mafaka8** [comment]
I can write to /root. that is not the problem. 

root filesystem is no where near close to full lol 

Filesystem               Size  Used Avail Use% Mounted on
/dev/mapper/centos-root   50G   36G   15G  72% /
devtmpfs                 3.8G     0  3.8G   0% /dev
tmpfs                    3.8G   16K  3.8G   1% /dev/shm
tmpfs                    3.8G  9.9M  3.8G   1% /run
tmpfs                    3.8G     0  3.8G   0% /sys/fs/cgroup
/dev/sda1               1014M  305M  710M  31% /boot
/dev/mapper/centos-home   40G  9.5G   31G  24% /home
tmpfs                    777M   28K  777M   1% /run/user/0

The problem is that there needs to be a unique identifier per thread configuration in the amd.txt file.

**Comment by psychocrypt** [comment]
Normally there is not need for a unique identifier as you can see on your
other system.
Never the less I will add an option to ignore the compiler cashe but still
try to uderstand whats going on.

**Comment by Mafaka8** [comment]
yeah me too id like to understand what is going on - you are 100% correct I forgot that on my other system everything works properly.

Do you think it might have something to do with how clinfo is retrieving the data? the clinfo version on my centOS rig is not the same as the version on the Ubuntu box.

**Comment by psychocrypt** [comment]
No clinfo is only a tool like the mier to give you an overview about the
opencl devices.
Could you please recomoile the miner with the original unchanged code and
add to cmake the option `-DCMAKE_BUILD_TYPE=Debug`
Than start the miner by hand with `gdb -ex r -ex bt --args ./xmr-stak`
This will show me which line forces the segfault

**Comment by psychocrypt** [comment]
option add in #1239

**Comment by psychocrypt** [comment]
reopened we need to find the segfault^^

**Comment by Mafaka8** [comment]
Is this what you need?

This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /root/Desktop/moneroMinning/temp/xmr-stak/build/bin/xmr-stak...done.
Starting program: /root/Desktop/moneroMinning/temp/xmr-stak/build/bin/./xmr-stak
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[2018-03-28 01:17:01] : MEMORY ALLOC FAILED: mmap failed
[2018-03-28 01:17:01] : MEMORY ALLOC FAILED: mmap failed
[2018-03-28 01:17:01] : MEMORY ALLOC FAILED: mmap failed
[2018-03-28 01:17:01] : MEMORY ALLOC FAILED: mmap failed
[2018-03-28 01:17:01] : MEMORY ALLOC FAILED: mmap failed
[New Thread 0x7ffff3218700 (LWP 21655)]
-------------------------------------------------------------------
xmr-stak 2.3.0 a036cd8

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-03-28 01:17:01] : Mining coin: monero7
[New Thread 0x7ffff2a17700 (LWP 21656)]
Missing separate debuginfo for /usr/lib/libOpenCL.so.1
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/ce/08d6a8a027e1b0643673811866f369858d160d.debug
[2018-03-28 01:17:01] : Compiling code and initializing GPUs. This will take a while...
[New Thread 0x7fffe0c34700 (LWP 21661)]
[2018-03-28 01:17:03] : Device 0 work size 8 / 32.
[New Thread 0x7fffdf329700 (LWP 21666)]
[2018-03-28 01:17:04] : OpenCL device 0 - Precompiled code /root/.openclcache/e84b19025965ac5f4296fc19b6df55de888c903a53a6b001aa046ab6e130b853.openclbin not found. Compiling ...
/root/.openclcache/e84b19025965ac5f4296fc19b6df55de888c903a53a6b001aa046ab6e130b853.openclbin
[2018-03-28 01:17:20] : OpenCL device 0 - Precompiled code stored in file /root/.openclcache/e84b19025965ac5f4296fc19b6df55de888c903a53a6b001aa046ab6e130b853.openclbin
[2018-03-28 01:17:20] : Device 0 work size 8 / 32.
[New Thread 0x7fffde9e2700 (LWP 21676)]
[2018-03-28 01:17:21] : OpenCL device 0 - Load precompiled cod from file /root/.openclcache/e84b19025965ac5f4296fc19b6df55de888c903a53a6b001aa046ab6e130b853.openclbin

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff2a17700 (LWP 21656)]
0x00007fffec1f20c0 in ?? ()
#0  0x00007fffec1f20c0 in ?? ()
#1  0x00007fffe155fa8a in ?? () from /usr/lib/libamdocl12cl64.so
#2  0x00007fffe156020c in ?? () from /usr/lib/libamdocl12cl64.so
#3  0x00007fffe1562451 in ?? () from /usr/lib/libamdocl12cl64.so
#4  0x00007fffe18eb8ec in ?? () from /usr/lib/libamdocl12cl64.so
#5  0x00007fffe808a249 in ?? () from /opt/amdgpu-pro/lib64/libamdocl64.so
#6  0x00007fffe80690a5 in clCreateProgramWithBinary () from /opt/amdgpu-pro/lib64/libamdocl64.so
#7  0x00007ffff1bd2a9a in clCreateProgramWithBinary () from /usr/lib/libOpenCL.so.1
#8  0x00007ffff1ec9198 in InitOpenCLGpu (opencl_ctx=0x7fffec9b0ef0, ctx=0x7fffec003ea0,
    source_code=0x7fffec9db618 "\n/*\n  * This program is free software: you can redistribute it and/or modify\n  * it under the terms of the GNU General Public License as published by\n  * the Free Software Foundation, either version 3"...)
    at /root/Desktop/moneroMinning/temp/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.cpp:505
#9  0x00007ffff1ecb064 in InitOpenCL (ctx=0x7fffec003dc0, num_gpus=6, platform_idx=0)
    at /root/Desktop/moneroMinning/temp/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.cpp:871
#10 0x00007ffff1f01336 in xmrstak::amd::minethd::init_gpus () at /root/Desktop/moneroMinning/temp/xmr-stak/xmrstak/backend/amd/minethd.cpp:104
#11 0x00007ffff1f0143e in xmrstak::amd::minethd::thread_starter (threadOffset=0, pWork=...)
    at /root/Desktop/moneroMinning/temp/xmr-stak/xmrstak/backend/amd/minethd.cpp:127
#12 0x00007ffff1f011b4 in xmrstak::amd::xmrstak_start_backend (threadOffset=0, pWork=..., env=...)
    at /root/Desktop/moneroMinning/temp/xmr-stak/xmrstak/backend/amd/minethd.cpp:81
#13 0x000000000043e282 in xmrstak::plugin::startBackend (this=0x7ffff2a16630, threadOffset=0, pWork=..., env=...)
    at /root/Desktop/moneroMinning/temp/xmr-stak/xmrstak/backend/plugin.hpp:88
#14 0x000000000043db65 in xmrstak::BackendConnector::thread_starter (pWork=...)
    at /root/Desktop/moneroMinning/temp/xmr-stak/xmrstak/backend/backendConnector.cpp:81
#15 0x0000000000442998 in executor::ex_main (this=0x76b920) at /root/Desktop/moneroMinning/temp/xmr-stak/xmrstak/misc/executor.cpp:495
#16 0x00000000004359a3 in std::_Mem_fn_base<void (executor::*)(), true>::operator()<, void>(executor*) const (this=0x76bd70, __object=0x76b920)
    at /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/functional:600
#17 0x0000000000435937 in std::_Bind_simple<std::_Mem_fn<void (executor::*)()> (executor*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x76bd68)
    at /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/functional:1531
#18 0x00000000004357e7 in std::_Bind_simple<std::_Mem_fn<void (executor::*)()> (executor*)>::operator()() (this=0x76bd68)
    at /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/functional:1520
#19 0x0000000000435746 in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (executor::*)()> (executor*)> >::_M_run() (this=0x76bd50)
    at /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/thread:115
#20 0x00007ffff6bd19c0 in std::execute_native_thread_routine (__p=<optimized out>) at ../../../.././libstdc++-v3/src/c++11/thread.cc:84
#21 0x00007ffff7bc6e25 in start_thread (arg=0x7ffff2a17700) at pthread_create.c:308
#22 0x00007ffff633834d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
Missing separate debuginfos, use: debuginfo-install elfutils-libelf-0.168-8.el7.x86_64 pciutils-libs-3.5.1-2.el7.x86_64
